version: '3.1'

services:
  db:
    ports:
      - '5432:5432'
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: note-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aboba

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
